[tool.poetry]
name = "generate-fractals"
version = "0.1.0"
description = ""
authors = ["tidywave"]

[tool.poetry.dependencies]
python = "^3.10"
svg-turtle = "^0.4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
